### ISSUE TITLE
Error occurs when trying to run WEC-Sim examples

### ISSUE THREAD

**Issue by Naveenudara** [WEC-Sim/WEC-Sim#754] opened 2021-10-24 07:44 UTC
**Note: italicized text below is include as an example and should be updated before submission. If you feel any section is not applicable to your request, please replace with 'N/A' rather than delete a section.**

**Cite the [WEC-Sim applications](https://github.com/WEC-Sim/WEC-Sim_Applications) case in question**
_C:\Users\udara\AppData\Roaming\MathWorks\MATLAB Add-Ons\Collections\WEC-Sim\examples\RM3_

**Describe the bug or issue**
_When I run the WEC-Sim examples as describe in WEC-Sim tutorials, I got error call "Function 'quaternion2EulXYZ' not supported for code generation."   _

**To Reproduce**
_Steps to reproduce the behavior:_

1. _Go to 'examples'.._
1. _Click on 'Relevant xxx.slx file.'_
1. _Scroll down to 'run WecSim'_
1. _See error_

**Expected behavior**
_I want to run the examples first but it did not run._

**Screenshots**
_Relevant screenshots are attached ._
![1](https://user-images.githubusercontent.com/92772032/138585037-d800bb4c-1def-4242-bef2-3b6cecd3caa6.PNG)
![2](https://user-images.githubusercontent.com/92772032/138585040-4cdc7445-9dcd-493a-aec7-40d5fa6e15e5.PNG)
![3](https://user-images.githubusercontent.com/92772032/138585041-50317956-5cb2-430b-bcc3-1acedcf08922.PNG)
![4](https://user-images.githubusercontent.com/92772032/138585043-141cf6d4-0833-4a29-a751-1f55d676c463.PNG)

**Workstation Information (this section MUST BE completed):**
 - OS: [Windows 7]
 - [MATLAB/Simulink Release][2021a]
 - [WEC-Sim Release][ v4.3]

**Additional context**
_I am just a beginner in WEC-Sim and just trying to run examples and tutorials as a beginning._

**Comment by nathanmtom** [comment] 2021-10-29 20:27
@Naveenudara Thank you for the clarification, if you were trying to use our run from Simulink option there may have been some additional steps you would have needed to follow; however, your responses indicate that this is not the case. 

Unfortunately, I am unable to reproduce your error based on your description above. My first suggestion would be to make sure you have the correct path in MATLAB to your WEC-Sim folder. Second is that a new WEC-Sim version has just been released and use GitHub to pull the latest changes into you local files and try again.

If the above does not solve your issues, then I will need a much more detailed step-by-step process to trouble shoot your unique difficulty running our example cases. 

Cheers, 
Nathan
National Renewable Energy Laboratory

**Comment by nathanmtom** [comment] 2021-11-05 19:04
@Naveenudara I wanted to follow-up on this discussion and was hoping to hear if you could answer some of my questions above? 

I'd also recommend double checking that you have set the correct `Path` within MATLAB to make sure that all files in the WEC-Sim source directory can be found when you execute WEC-Sim. 

If we do not hear back from you in another week we will assume the issue has been resolved and we will close this issue.

Cheers, 
Nathan
National Renewable Energy Laboratory

**Closed** 2021-11-17 15:25 UTC
Labels: Support
