### ISSUE TITLE
[BUG] Parallel Computing Toolbox (PCT)

### ISSUE THREAD

**Issue by zash07** [WEC-Sim/WEC-Sim#782] opened 2021-12-17 14:14 UTC
**Note: italicized text below is included as an example and should be updated before submission. If you feel any section is not applicable to your request, please replace with 'N/A' rather than delete a section.**

**Describe the bug**
_The parallel computing (PCT), did not work for me even for the RM3 example._

**WEC-Sim file(s)**
_N/A_

**To Reproduce**
_Steps to reproduce the behavior:_
1. _Go to 'Rm3 example'_
2. _Click on 'to run pct '_
3. _Scroll down to 'command window'_
4. _See error_

**Expected behavior**
_To be able to work with PCT._

**Screenshots**
_I provide an error for my case the same error can be seen for RM3 original example._
![image](https://user-images.githubusercontent.com/92889661/146556624-b5849429-3cd8-447d-9bb2-77c70e952241.png)

**Workstation Information (this section MUST BE completed):**
 - OS: [Windows 10]
 - [MATLAB/Simulink Release](https://www.mathworks.com/help/matlab/release-notes.html) [2020b]
 - [WEC-Sim Release](http://wec-sim.github.io/WEC-Sim/man/release_notes.html) [Version: 4.3]

**Additional context**
_I wrote the following scripts for parallel computing to run for different sea states and I could solve my problem following that._
![image](https://user-images.githubusercontent.com/92889661/146557252-b89b376b-d658-41c0-86d7-6f4da27828fe.png)
 
![image](https://user-images.githubusercontent.com/92889661/146557302-bc8044cf-c63d-41f0-92a3-66b24d463500.png)

**Comment by dav-og** [comment] 2021-12-22 15:30
Hoping @jleonqu can help out with this when he's back

**Comment by jleonqu** [comment] 2022-01-11 02:50
Hello @zash07 

I would say the problem is that the information needed to run the simulation is not available for all the workers created with the parfor command. There are some specific restrictions when running simulink models within parfor. In the current documentation in the Mathworks webpage there is an explicit recommendation for not using the sim function within parfor, see this [link](https://www.mathworks.com/help/simulink/ug/not-recommended-using-sim-function-within-parfor.html). The other option is to use parsim, which could be the solution you are looking for.

Another option to solve this issue is to use the Sensitivity Analyzer tool in Simulink (documentation [here](https://www.mathworks.com/help/sldo/ref/sensitivityanalyzer-app.html) ) and the Sensitivity Analysis options in Matlab (documentation [here](https://www.mathworks.com/help/sldo/sensitivity-analysis.html) ). I have used these options in the past for some other projects and it works well. My recommendation for you is to use these options when running a large amount of cases.

**Comment by jleonqu** [comment] 2022-02-02 16:01
Hello @zash07 
Does this answer help?

**Comment by zash07** [comment] 2022-02-03 07:18
Hello,

I sorted my problem in another way as I mentioned it.  Therefore, I just wanted to inform you about the problem. I do not have time to check other solutions at the moment. However, if they are reliable, I suggest that to be included in the manual description, it would be great for others with the same problem as I faced.

Best regards

**Comment by jleonqu** [comment] 2022-02-08 17:51
Thanks for your answer. I'll close this issue, but feel free to ask more questions or open a new one if needed.

**Comment by kmruehl** [comment] 2022-03-10 21:15
from @yuyihsiang 

Hi All,

I noticed that there was a discussion on the issue #782 regarding wecSimPCT. I ran into the same issue when running some WEC-Sim cases myself.

The issue is that the way the code was written forces the wecSim run to be executed inside the computing working directory, which is generated when calling the parfor. In the past we had a few lines of the code inside wecSim.m file to change the directory back to the main working directly before calling the sim function and move back inside the computing working directory after the sim function is done. However, that part of the code does not exist anymore. I am note sure if there is a reason why it was removed. I think we should try to put it back if possible.

Best,

--Yi-Hsiang

**Comment by kmruehl** [comment] 2022-03-10 21:16
I have also run into this issue

```matlab

Simulating the WEC device defined in the SimMechanics model C:\Users\kmruehl\Documents\GitHub\WEC-Sim\WEC-Sim_Applications\Multiple_Condition_Runs\RM3_MCROPT1\RM3.slx...   
Elapsed time is 9.171886 seconds.
Error using wecSim (line 46)
No system or file called 'RM3.slx' found.

Error in wecSimFcn (line 23)
wecSim

Error in wecSimPCT (line 102)
parfor imcr=1:length(mcr.cases(:,1))

```

**Comment by kmruehl** [comment] 2022-03-17 22:44
@yuyihsiang  this issue has been resolved, thanks @akeeste for the help!

**Closed** 2022-03-17 22:44 UTC
Labels: Bug, MCR/PCT
