### ISSUE TITLE
Nonlinear Hydro Body for OSWEC Tutorial

### ISSUE THREAD

**Issue by brittlyd** [WEC-Sim/WEC-Sim#903] opened 2022-07-05 18:53 UTC
I am trying to run the OSWEC tutorial with the flap being a nonlinear hydro body (body(1).nonlinearHydro = 2) and saving the pressure distribution (simu.pressure = 1). I was able to successfully run this last week (at least I thought I was..), but now when I try to run the tutorial with these two lines of code added, I get the following error:

Error using wecSim (line 45)
Error due to multiple causes.
Caused by:
    Error using wecSim (line 45)
    Simulink cannot determine sizes and/or types of the outputs for block 'OSWEC/Flap/Hydrodynamic Body/Nonlinear Wave Elevation/Linear or Instantaneous Free Surface/Instantaneous Water Free Surface/Instantaneous FS' due to errors in the block body, or limitations of the underlying analysis. The errors might be inaccurate. Fix the indicated errors, or explicitly specify sizes and/or types for all block outputs.
    Error using wecSim (line 45)
    Error in port widths or dimensions. 'Output Port 1' of 'OSWEC/Flap/Hydrodynamic Body/Nonlinear Wave Elevation/Linear or Instantaneous Free Surface/Instantaneous Water Free Surface/Instantaneous FS/x' has 6 elements.  This port does not accept the dimensions (or orientation) specified by the output signal.
 
The tutorial runs fine without these edits, and I'm not sure how to fix these errors. Thanks for your help!

**Comment by nathanmtom** [comment] 2022-07-08 04:30
@brittlyd Thank you for submitting your issue. Before we are able to answer your question we ask that you edit the existing issue to follow one of our issue templates. An example of our template is shown below for reference.

![image](https://user-images.githubusercontent.com/7635064/177917100-a4831942-03bd-4999-90a2-b959feccc2ba.png)

**Comment by nathanmtom** [comment] 2022-07-14 15:57
@brittlyd Thank you for updating your issue to one of our templates! This really helps so that the WEC-Sim team obtains most of the information we need to understand the issue and the process you have taken to encounter this issue. 

I was able to reproduce your error using the OSWEC Example (rather than OSWEC Tutorial) and found that the issue is that the OSWEC Example has wave directional spreading in lines 28 and 29. 

`waves.direction = [0, 30, 90]`
`waves.spread = [0.1, 0.2, 0.7]`

If you comment out those two lines and re-run WEC-Sim the simulation should run to completion and the pressure data stored as describe by the WEC-Sim document. 

Unfortunately, the nonlinear hydrodynamic feature does not currently support the wave directional spreading option. Hopefully, you can proceed with your work without needing this functionality. If you need this functionality for your work, please let us know and we can try to prioritize enabling this functionality in the future. 

Cheers, 
Nathan
National Renewable Energy Laboratory

**Comment by brittlyd** [comment] 2022-07-26 19:36
Hi Nathan,

Thank you for your help! I am now able to run WEC-Sim with a nonlinear hydro flap for both regular and irregular waves. I do have a follow-up question. When adding the nonlinear hydro flap for just the standard regular wave, the resulting excitation and buoyancy force are very noisy and it looks like it is likely caused by numerical artifacts (see attached photo). I was wondering if there were simulation parameters I could mess with to help smooth out the signal? I tried adjusting the time step and the ode solver to ode45, but saw little change. I'm wondering if it could be an issue of spatial resolution? See details below:

**WEC-Sim application:**
I am trying to change the OSWEC tutorial to include the flap as a nonlinear hydrodynamic body.

**Issue:**
The output excitation and buoyancy torques/forces are very noisy/spiky with what looks like numerical artifacts.

**To Reproduce:**

1. Start with original OSWEC example input file
2.  Set simu.dt = 0.01;
3. Set simu.endTime = 200;
4. Add body(1).nonlinearHydro = 2; in the third section
5. Make sure the regular wave section is uncommented in the wave information section of the code (H = 2.5, T = 8)

**Expected behavior:**
I'm hoping to get a smoother output for excitation and restoring torques/forces.

**Screenshots**
I attached a plot of my output of excitation torque (pitch), restoring torque (pitch), excitation force (surge), restoring force (surge). 
![wecSimNonLinear](https://user-images.githubusercontent.com/60209345/181096853-77cb9e11-54b0-4b8a-a4f9-59c34603bffa.jpg)

**Comment by nathanmtom** [comment] 2022-07-27 05:52
@brittlyd Thank you for confirming you are able to now run the OSWEC example with the nonlinearHydro option. If you are using the .stl file that comes with the OSWEC example, then I would attribute the noisy and spiky data to the coarse resolution of the .stl mesh. If you would like to improve the output signals then I would suggest generating a new .stl file with finer resolution as the other parameters you have listed are likely to not influence how the pressure is integrated over the body shape.

Cheers, 
Nathan
National Renewable Energy Laboratory

**Comment by nathanmtom** [comment] 2022-08-03 14:11
@brittlyd I wanted to check in to see if you had any further questions related to the OSWEC example with the nonlinearHydro option? If we do not hear back from you by the end of this week we will close this issue. 

Cheers, 
Nathan
National Renewable Energy Laboratory

**Closed** 2022-08-05 22:34 UTC
