### ISSUE TITLE
only names in bodiesOutput

### ISSUE THREAD

**Issue by avidortelem** [WEC-Sim/WEC-Sim#334] opened 2020-02-03 13:45 UTC
Hello,

I am new to WEC SIM and I try to play a bit with the tool to understand how it works,

I often have the following error when I run some models:

When I run wecSim it looks to work (the system has a  movement in the visualisation)

until the error in responseClass.m row 40 , the bodiesOutput is only a 1*2 struct, there are only the names. (no time, no signals, etc...)

What could explain that the outputs are not here ?

What is weird is that, I can have two time the same model with exactly the same blocks and input files, and one where the error appears and the other not. (it looks like the one that are built by modifying the tutorials work, but the same model build by myself does not work, and except the color of the block in the simulink models, there is absolutely no differences)

Thank you very much.
Br Telem

**Comment by kmruehl** [comment] 2020-02-19 20:16
@avidortelem Thank you for your question and my apologies for the delay in response. Could you please upload a ZIP file with this WEC-Sim model so that I can resolve this issue? Thank you.

**Comment by avidortelem** [comment] 2020-02-20 10:52
Thanks !

I update an example in ZIP.

I use my nemoh outputs on a plate to run WECSIM with a surge constraints.

I use the flap geometry just for the visualisation.

I don't know if the error comes from my nemoh outputs or from something else..

Thanks again 
[model.zip](https://github.com/WEC-Sim/WEC-Sim/files/4230278/model.zip)

**Comment by avidortelem** [comment] 2020-03-03 09:20
Hi,

I did the simulation with hydrodata from wamit files and the error is still here...

Br T

**Comment by avidortelem** [comment] 2020-03-03 10:07
An other remark:

If I modified the OSWEC tutorial to make {FLAP+BASE} move surge according to global frame --> IT WORKS

If I built EXACTLY the same model but I do it manually from scratch --> it DOES NOT work 

Crazy..

**Comment by avidortelem** [comment] 2020-03-10 13:11
Hello @kmruehl do you have an idea when you look at the pictures above ?

Sorry to notify you but I really don't understand and I am block :/. I compared all the inputs (body, simu, waves, etc..)  when I run the simulations and there is no differences, so I really think the error comes from the simulink models. 

Br T

**Comment by dforbush2** [comment] 2020-03-10 21:21
Hi @avidortelem 

I'm new to your issue, but the little chain thing you have pointed out means that the block is "library linked" and it is referencing the WEC-Sim simulink library.

The fact that your "from scratch" simulink model does not have this could explain why your output file has only names if the link is somehow broken. I unfortunately cannot open your simulink model, as it is in 2019b. Could you please reattach with the model saved 2019a or earlier? See "Export a Model to a Previous Simulink Version". https://www.mathworks.com/help/simulink/ug/saving-a-model.html

As a short term solution, is it possible to copy/paste the needed blocks from tutorial and example files? They should be properly linked to the library and can be initialized and specified as needed from the WEC-Sim input files. I usually use this approach when I make a new model anyway.

**Comment by avidortelem** [comment] 2020-03-11 11:26
Hi @dforbush2 , 

Thanks for your answer.

I put enclosed a zip of the model.

There is several simulink models and we can see that according to the one we choose the simulation works or no:

- one simulink model made from OSWEC --> WORK
- the same one made from scratch --> DOES NOT WORK
- the same one made from scratch same in previous version (can you open it now ?) --> DOES NOT WORK
- the same one made by copying the block in a blank model --> DOES NOT WORK.

I think the 'link' thing was just an issue of display because finally I can see it now ...

**Comment by dforbush2** [comment] 2020-03-11 14:25
Hi @avidortelem ,

I was able to replicate your error using my own clone of the repository. Thank you for bringing this to our attention.

We have identified an issue with the library link that is causing this error, and are working on a fix. In the meantime, I would recommend copy/pasting the necessary blocks from a tutorial/example or applications case (https://github.com/WEC-Sim/WEC-Sim_Applications). Any block you might need should be found in one of those locations. Thank you for bringing this to our attention, and apologies for the delay in addressing your issue. 

I will reply once more and close this issue when the error has been resolved.

**Comment by avidortelem** [comment] 2020-03-12 14:58
Thank you very much ! I succeed to make it work now.

PS: 
It seems that it works when I use the simulink file of a tutorial, whatever if it is my block or not.
If I use a new blank simulink model and I copy the block from the tutorials, it doest not work.

Br T

**Comment by nathanmtom** [comment] 2020-03-23 20:30
@avidortelem Thank you for your patience awaiting our response to the issue you have raised. After further investigation, the WECSim team identified the issue is with the default parameters set in the "Model Configuration Parameters" by MATLAB. Starting in MATLAB 2019a a newly created .slx file will have a check box titled "Single Simulation Ouput" checked which causes the issue that you submitted with this issue request. If you un-check this option in the .slx file, save, and run WECSim the postProcess script should no longer have the issue you raised. 

The team has now added a check within the simulationClass.m to ensure that any new .slx files generated will have the option unchecked. If possible, please pull the latest version of WECSim from the Github website and check that a .slx file created from scratch will now execute properly. 

Please let us know if this hasn't solved your issue. 

Cheers, 
Nathan (National Renewable Energy Laboratory)

**Comment by avidortelem** [comment] 2020-03-24 09:29
Hello,

It seems to work now for me. Thanks you very much for your help :) !

**Closed** 2020-03-24 15:05 UTC
Labels: bug, question
