### ISSUE TITLE
[WEC-Sim Applications] Read_AQWA error line 134

### ISSUE THREAD

**Issue by haniyehtp** [WEC-Sim/WEC-Sim#734] opened 2021-10-07 15:23 UTC
**Note: italicized text below is include as an example and should be updated before submission. If you feel any section is not applicable to your request, please replace with 'N/A' rather than delete a section.**

**Cite the [WEC-Sim applications](https://github.com/WEC-Sim/WEC-Sim_Applications) case in question**
_Please identify the WEC-Sim applications case in question._

**Describe the bug or issue**
I get an error while running BEMIO for an AQWA hydro file. The error occurs in line 134 of Read_AQWA and it says the size of the left side is 1-by-6 and the size of the right side is 0-by-0. My model has 5 bodies. And my Ansys version is 18.2

**To Reproduce**
1. _Copy the hydrodata files to BEMIO>AQWA>EXAMPLE
2. _Run the BEMIO file in Matlab.

**Expected behavior**
I expected it to run normally and produce the .h5 file.

**Screenshots**
![image](https://user-images.githubusercontent.com/87119040/136412068-406d864c-96e1-4184-bc37-b837e5b65c53.png)

**Workstation Information (this section MUST BE completed):**
 - OS: [Windows 10]
 - [MATLAB/Simulink Release] [2020b]
 - [WEC-Sim Release] [v4.2]
 - [ANSYS] [v18.2]

**Additional context**
hydrodata file:
[ANALYSIS.zip](https://github.com/WEC-Sim/WEC-Sim/files/7304882/ANALYSIS.zip)

Thank you in advance
Haniyeh

**Comment by jtgrasb** [comment] 2021-10-11 15:01
Thank you for notifying us of the issue. The team is currently working on updating our AQWA compatibility and actually came across this same issue recently. The issue is due to AQWA's approach to interactions between bodies in terms of the added mass data. Usually, AQWA includes coupling between bodies when recording the added mass, but when some bodies are far apart, this coupling is not recorded. This discrepancy has previously not been taken into account in the Read_AQWA.m function, but is fixed by initializing some of the storage variables and breaking the loop if the line where coupling is expected is found to be empty. 

PR #694 solves this issue and should be merged with the dev branch soon.

**Closed as completed** 2021-10-20 14:16 UTC
Labels: AQWA
