### ISSUE TITLE
NEED urgent guidance WEC-Sim

### ISSUE THREAD

**Issue by muzammilhuss** [WEC-Sim/WEC-Sim#291] opened 2019-04-06 10:54 UTC
Hello, Dear members,
I successfully added up WEC-sim blocks in a SImulink Library. I am new to matlab. but not very expert yet.
My issue is that, since 3 days of struggle, I found that, this code does not run smoothly in 2018b. I tried it on 2018a as well. its gives same errors. there is a chance that I am not doing something correct. but I definitely want to find out where am I not doing correct. 
These two errors are shown in screen shot. Please guide me, how to get rid of them?
These errors are not going away. no matter i do. I had downloaded full .h5 files too. I am just worried. Thanks.

![image](https://user-images.githubusercontent.com/49338779/55668497-af8eec80-589d-11e9-9719-15f2ecbd67c4.png)
![image](https://user-images.githubusercontent.com/49338779/55670398-4798d000-58b6-11e9-95a4-9741feb116fd.png)

**Comment by yuyihsiang** [comment] 2019-04-08 15:16
I believe you did not have the h5 files in the correct folder.
The error message is saying that the file it was looking for is basically 0k. 
You have to download and REPLACE the files in the hydroData folder inside each case (e.g., inside the RM3 and OSWEC tutorials).

YI-Hsiang

**Comment by muzammilhuss** [comment] 2019-04-09 11:37
Thank you so much Yl-Hsiang. Problem solved. simulation is able to run smoothly. 
But, I would like to know that, although the simulation runs, but I am not able to use PTOSim_Lib, generator blocks from Matlab library tree which have been added by me. I mean, when I give some constant value and add it into new project, It asks me for ptosim.pmRotaryGenerator(1) . Which files I have to run? so that i can use those blocks for my study.
Also, for classes, mooring, PTO etc ....e.g., 
if,
constraint(#) = constraintClass('<Constraint name>')
then,
what could be the constraint name? Do I must have to give it a name? if yes, then what that is supposed to be? Give me an example.
I already studied from the website, and I did not get the idea of it. How to do?
![image](https://user-images.githubusercontent.com/49338779/55797285-a0f34000-5afe-11e9-99c4-755b842a24eb.png)
My major purpose if use build in WEC ( library) block presented by you.... 
Thank you

**Comment by kmruehl** [comment] 2019-04-11 14:58
@muzammilhuss this error is likely due to the fact that there are several PTO parameters that are defined in the `ptoSimInputFile.m`. The `ptoSimInputFile.m` must be fined to define there parameters. For examples of these files, refer to the WEC-SIm_Applications repository, in the PTO-Sim directory, [here](https://github.com/WEC-Sim/WEC-Sim_Applications/tree/master/PTO-Sim).  And for more information about PTO-Sim, refer to the documentation [here](http://wec-sim.github.io/WEC-Sim/advanced_features.html#power-take-off-pto-sim).

**Comment by kmruehl** [comment] 2019-04-18 21:58
@muzammilhuss did this resolve your issue?

**Comment by muzammilhuss** [comment] 2019-04-19 16:13
Hi thanks. This is the error. Well, its so complex. every time new error comes. how to fix this library now? 
![image](https://user-images.githubusercontent.com/49338779/56432712-04504f80-6301-11e9-8b06-3592607c3157.png)

**Comment by kmruehl** [comment] 2019-04-22 21:27
@muzammilhuss it looks like there were a few broken library links in the PTO-Sim example files on the WEC-Sim_Applications repository (https://github.com/WEC-Sim/WEC-Sim_Applications). I just updated the library links for the`Rotary Generator Lookup Table` for the case you were running, and now the `OSWEC_Hydraulic_Crank_PTO` case should run without error. Please pull the latest version of the WEC-Sim_Applications repository to resolve this issue. 

![image](https://user-images.githubusercontent.com/4603379/56531744-c5ddaf00-6511-11e9-936c-25a45138c4eb.png)

![image](https://user-images.githubusercontent.com/4603379/56531825-e73e9b00-6511-11e9-947f-60325b8cfdae.png)

**Comment by muzammilhuss** [comment] 2019-04-25 13:51
I think this is a bug... which needs to be fixed. How to do?
![image](https://user-images.githubusercontent.com/49338779/56740733-14a27780-67a4-11e9-9fca-bd3daf40b141.png)

**Comment by kmruehl** [comment] 2019-04-25 15:31
@muzammilhuss It looks like you're running WEC-Sim from the Source Directory, not the Case Directory. To run WEC-Sim, you must be in the Case Directory, and execute WEC-Sim by typing `wecSim` into the command window. 

The error related to the convolution integral time is because `simu.CITime` is larger than the impulse response function for the available hydrodynamic data. This can be resolved by reducing `simu.CITime`  in the `wecSimInputFile.m`

For more information on running WEC-Sim, refer to documentation here:
http://wec-sim.github.io/WEC-Sim/overview.html#running-wec-sim

**Comment by kmruehl** [comment] 2019-05-06 22:55
@muzammilhuss does this resolve your issue?

**Comment by muzammilhuss** [comment] 2019-05-07 03:59
Thank ypou very much. some fo the issues have been resolved successfully. But I think this error is about something else. this error comes when I runs "wecSiminutfile.m" of irregularCIC and RM3_MoorDyn...

![image](https://user-images.githubusercontent.com/49338779/57270644-cacc6200-70be-11e9-8ee1-731a1459c79c.png)
![image](https://user-images.githubusercontent.com/49338779/57270707-05ce9580-70bf-11e9-8338-eb65fdaa4b33.png)

**Comment by kmruehl** [comment] 2019-05-07 15:52
@muzammilhuss I was able to run the RM3_MoorDyn simulations with `waveClass('etaImport');`, `waveClass('regularCIC')` and `waveClass('irregular')` on my machine without issue. There is not a waveClass called irregularCIC, see list of wave classes here: http://wec-sim.github.io/WEC-Sim/code_structure.html#wave-class. 

![image](https://user-images.githubusercontent.com/4603379/57313214-5b4d7700-70ac-11e9-9999-96329a1dfe24.png)

I believe the issue is that you are running WEC-Sim simulations from the **$SOURCE** directory, not the **$CASE** directory. Only the **$SOURCE** directory should be in your MATLAB path, and you must be in the **$CASE** directory to run the RM3_MoorDyn simulation. 

For me, the **$CASE** directory is: _C:\Users\kmruehl\Documents\GitHub\WEC-Sim\WEC-Sim\WEC-Sim_Applications\RM3_Mooring\RM3_MoorDyn_, and my **$SOURCE** directory is: _C:\Users\kmruehl\Documents\GitHub\WEC-Sim\WEC-Sim\source_.

**Comment by kmruehl** [comment] 2019-05-21 19:39
@muzammilhuss did this resolve your issue?

**Closed** 2019-05-30 21:43 UTC
Labels: BEMIO, power take-off
